[package]
name = "yaf2m"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Yet Another Feed to Mail: Send email on RSS feed update."

[dependencies]
ammonia = "=4.1.3"
ansi-to-html = "=0.2.3"
blake3 = "=1.8.5"
chrono = "=0.4.45"
color-eyre = "=0.6.5"
env_logger = "=0.11.11"
feed-rs = "=2.3.1"
humantime = "=2.3.0"
humantime-serde = "=1.1.1"
lettre = { version = "=0.11.22", default-features = false, features = ["builder", "pool", "smtp-transport", "serde", "tokio1-rustls", "aws-lc-rs", "webpki-roots"] }
log = "=0.4.33"
minijinja = { version = "=2.20.0", features = ["loader"] }
minijinja-contrib = { version = "=2.20.0", features = ["datetime", "timezone"] }
ouroboros = "=0.18.5"
regex = "=1.12.3"
reqwest = { version = "=0.13.4", default-features = false, features = ["charset", "http2", "system-proxy", "gzip", "rustls"] }
reqwest-middleware = "=0.5.2"
reqwest-retry = "=0.9.1"
serde = { version = "=1.0.228", features = ["derive"] }
serde_with = "=3.21.0"
sqlx = { version = "=0.9.0", features = ["postgres", "runtime-tokio", "chrono"] }
tokio = { version = "=1.52.3", features = ["rt-multi-thread", "macros", "time"] }
toml = "=1.1.2"
tracing = "=0.1.44"
